namespace PipeRack
{
    partial class Form_att
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label24 = new System.Windows.Forms.Label();
            this.PrefixSborki = new System.Windows.Forms.TextBox();
            this.Namen = new System.Windows.Forms.TextBox();
            this.label18 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.Material = new System.Windows.Forms.TextBox();
            this.Profile = new System.Windows.Forms.TextBox();
            this.label21 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.Class = new System.Windows.Forms.TextBox();
            this.NomerSborki = new System.Windows.Forms.TextBox();
            this.label26 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.button1 = new System.Windows.Forms.Button();
            this.PolojenieGorizontalno = new System.Windows.Forms.ComboBox();
            this.PolojeniePovorot = new System.Windows.Forms.ComboBox();
            this.PolojenieVertikalno = new System.Windows.Forms.ComboBox();
            this.profileCatalog1 = new Tekla.Structures.Dialog.UIControls.ProfileCatalog();
            this.materialCatalog1 = new Tekla.Structures.Dialog.UIControls.MaterialCatalog();
            this.SuspendLayout();
            // 
            // label24
            // 
            this.structuresExtender.SetAttributeName(this.label24, null);
            this.structuresExtender.SetAttributeTypeName(this.label24, null);
            this.structuresExtender.SetBindPropertyName(this.label24, null);
            this.label24.Location = new System.Drawing.Point(1, 117);
            this.label24.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(105, 16);
            this.label24.TabIndex = 127;
            this.label24.Text = "Нумерация сборок";
            this.label24.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // PrefixSborki
            // 
            this.structuresExtender.SetAttributeName(this.PrefixSborki, null);
            this.structuresExtender.SetAttributeTypeName(this.PrefixSborki, null);
            this.structuresExtender.SetBindPropertyName(this.PrefixSborki, null);
            this.PrefixSborki.Location = new System.Drawing.Point(111, 116);
            this.PrefixSborki.Name = "PrefixSborki";
            this.PrefixSborki.Size = new System.Drawing.Size(71, 20);
            this.PrefixSborki.TabIndex = 126;
            this.PrefixSborki.Text = "K";
            // 
            // Namen
            // 
            this.structuresExtender.SetAttributeName(this.Namen, null);
            this.structuresExtender.SetAttributeTypeName(this.Namen, null);
            this.structuresExtender.SetBindPropertyName(this.Namen, null);
            this.Namen.Location = new System.Drawing.Point(111, 6);
            this.Namen.Name = "Namen";
            this.Namen.Size = new System.Drawing.Size(148, 20);
            this.Namen.TabIndex = 123;
            this.Namen.Text = "Колонна";
            // 
            // label18
            // 
            this.structuresExtender.SetAttributeName(this.label18, null);
            this.structuresExtender.SetAttributeTypeName(this.label18, null);
            this.structuresExtender.SetBindPropertyName(this.label18, null);
            this.label18.Location = new System.Drawing.Point(11, 9);
            this.label18.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(60, 17);
            this.label18.TabIndex = 122;
            this.label18.Text = "Имя";
            this.label18.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label20
            // 
            this.structuresExtender.SetAttributeName(this.label20, null);
            this.structuresExtender.SetAttributeTypeName(this.label20, null);
            this.structuresExtender.SetBindPropertyName(this.label20, null);
            this.label20.Location = new System.Drawing.Point(11, 61);
            this.label20.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(60, 17);
            this.label20.TabIndex = 121;
            this.label20.Text = "Материал";
            this.label20.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // Material
            // 
            this.structuresExtender.SetAttributeName(this.Material, null);
            this.structuresExtender.SetAttributeTypeName(this.Material, null);
            this.structuresExtender.SetBindPropertyName(this.Material, null);
            this.Material.Location = new System.Drawing.Point(111, 58);
            this.Material.Name = "Material";
            this.Material.Size = new System.Drawing.Size(148, 20);
            this.Material.TabIndex = 120;
            this.Material.Text = "C345";
            // 
            // Profile
            // 
            this.structuresExtender.SetAttributeName(this.Profile, null);
            this.structuresExtender.SetAttributeTypeName(this.Profile, null);
            this.structuresExtender.SetBindPropertyName(this.Profile, null);
            this.Profile.Location = new System.Drawing.Point(111, 32);
            this.Profile.Name = "Profile";
            this.Profile.Size = new System.Drawing.Size(148, 20);
            this.Profile.TabIndex = 119;
            this.Profile.Text = "I30K1_20_93";
            // 
            // label21
            // 
            this.structuresExtender.SetAttributeName(this.label21, null);
            this.structuresExtender.SetAttributeTypeName(this.label21, null);
            this.structuresExtender.SetBindPropertyName(this.label21, null);
            this.label21.Location = new System.Drawing.Point(11, 35);
            this.label21.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(60, 17);
            this.label21.TabIndex = 118;
            this.label21.Text = "Профиль";
            this.label21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label2
            // 
            this.structuresExtender.SetAttributeName(this.label2, null);
            this.structuresExtender.SetAttributeTypeName(this.label2, null);
            this.structuresExtender.SetBindPropertyName(this.label2, null);
            this.label2.Location = new System.Drawing.Point(11, 198);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(83, 20);
            this.label2.TabIndex = 130;
            this.label2.Text = "Поворот";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label17
            // 
            this.structuresExtender.SetAttributeName(this.label17, null);
            this.structuresExtender.SetAttributeTypeName(this.label17, null);
            this.structuresExtender.SetBindPropertyName(this.label17, null);
            this.label17.Location = new System.Drawing.Point(11, 91);
            this.label17.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(60, 17);
            this.label17.TabIndex = 125;
            this.label17.Text = "Класс";
            this.label17.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // Class
            // 
            this.structuresExtender.SetAttributeName(this.Class, null);
            this.structuresExtender.SetAttributeTypeName(this.Class, null);
            this.structuresExtender.SetBindPropertyName(this.Class, null);
            this.Class.Location = new System.Drawing.Point(111, 87);
            this.Class.Name = "Class";
            this.Class.Size = new System.Drawing.Size(148, 20);
            this.Class.TabIndex = 124;
            this.Class.Text = "2";
            // 
            // NomerSborki
            // 
            this.structuresExtender.SetAttributeName(this.NomerSborki, null);
            this.structuresExtender.SetAttributeTypeName(this.NomerSborki, null);
            this.structuresExtender.SetBindPropertyName(this.NomerSborki, null);
            this.NomerSborki.Location = new System.Drawing.Point(188, 116);
            this.NomerSborki.Name = "NomerSborki";
            this.NomerSborki.Size = new System.Drawing.Size(71, 20);
            this.NomerSborki.TabIndex = 132;
            this.NomerSborki.Text = "2";
            // 
            // label26
            // 
            this.structuresExtender.SetAttributeName(this.label26, null);
            this.structuresExtender.SetAttributeTypeName(this.label26, null);
            this.structuresExtender.SetBindPropertyName(this.label26, null);
            this.label26.Location = new System.Drawing.Point(1, 174);
            this.label26.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label26.Name = "label26";
            this.label26.Size = new System.Drawing.Size(98, 17);
            this.label26.TabIndex = 114;
            this.label26.Text = "Вертикально";
            this.label26.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            this.structuresExtender.SetAttributeName(this.label3, null);
            this.structuresExtender.SetAttributeTypeName(this.label3, null);
            this.structuresExtender.SetBindPropertyName(this.label3, null);
            this.label3.Location = new System.Drawing.Point(22, 146);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(70, 18);
            this.label3.TabIndex = 133;
            this.label3.Text = "Положение";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label4
            // 
            this.structuresExtender.SetAttributeName(this.label4, null);
            this.structuresExtender.SetAttributeTypeName(this.label4, null);
            this.structuresExtender.SetBindPropertyName(this.label4, null);
            this.label4.Location = new System.Drawing.Point(1, 226);
            this.label4.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(98, 17);
            this.label4.TabIndex = 134;
            this.label4.Text = "Горизонтально";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // button1
            // 
            this.structuresExtender.SetAttributeName(this.button1, null);
            this.structuresExtender.SetAttributeTypeName(this.button1, null);
            this.structuresExtender.SetBindPropertyName(this.button1, null);
            this.button1.Location = new System.Drawing.Point(111, 252);
            this.button1.Margin = new System.Windows.Forms.Padding(2);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(68, 25);
            this.button1.TabIndex = 136;
            this.button1.Text = "Сохранить";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.Button1_Click);
            // 
            // PolojenieGorizontalno
            // 
            this.structuresExtender.SetAttributeName(this.PolojenieGorizontalno, null);
            this.structuresExtender.SetAttributeTypeName(this.PolojenieGorizontalno, null);
            this.structuresExtender.SetBindPropertyName(this.PolojenieGorizontalno, null);
            this.PolojenieGorizontalno.FormattingEnabled = true;
            this.PolojenieGorizontalno.Items.AddRange(new object[] {
            "Центр",
            "Слева",
            "Справа"});
            this.PolojenieGorizontalno.Location = new System.Drawing.Point(111, 225);
            this.PolojenieGorizontalno.Margin = new System.Windows.Forms.Padding(2);
            this.PolojenieGorizontalno.Name = "PolojenieGorizontalno";
            this.PolojenieGorizontalno.Size = new System.Drawing.Size(148, 21);
            this.PolojenieGorizontalno.TabIndex = 137;
            this.PolojenieGorizontalno.Text = "Центр";
            // 
            // PolojeniePovorot
            // 
            this.structuresExtender.SetAttributeName(this.PolojeniePovorot, null);
            this.structuresExtender.SetAttributeTypeName(this.PolojeniePovorot, null);
            this.structuresExtender.SetBindPropertyName(this.PolojeniePovorot, null);
            this.PolojeniePovorot.FormattingEnabled = true;
            this.PolojeniePovorot.Items.AddRange(new object[] {
            "Спереди",
            "Сверху",
            "Сзади",
            "Снизу"});
            this.PolojeniePovorot.Location = new System.Drawing.Point(111, 199);
            this.PolojeniePovorot.Margin = new System.Windows.Forms.Padding(2);
            this.PolojeniePovorot.Name = "PolojeniePovorot";
            this.PolojeniePovorot.Size = new System.Drawing.Size(148, 21);
            this.PolojeniePovorot.TabIndex = 138;
            this.PolojeniePovorot.Text = "Спереди";
            // 
            // PolojenieVertikalno
            // 
            this.structuresExtender.SetAttributeName(this.PolojenieVertikalno, null);
            this.structuresExtender.SetAttributeTypeName(this.PolojenieVertikalno, null);
            this.structuresExtender.SetBindPropertyName(this.PolojenieVertikalno, null);
            this.PolojenieVertikalno.FormattingEnabled = true;
            this.PolojenieVertikalno.Items.AddRange(new object[] {
            "Середина",
            "Вверх",
            "Вниз"});
            this.PolojenieVertikalno.Location = new System.Drawing.Point(111, 173);
            this.PolojenieVertikalno.Margin = new System.Windows.Forms.Padding(2);
            this.PolojenieVertikalno.Name = "PolojenieVertikalno";
            this.PolojenieVertikalno.Size = new System.Drawing.Size(148, 21);
            this.PolojenieVertikalno.TabIndex = 138;
            this.PolojenieVertikalno.Text = "Середина";
            // 
            // profileCatalog1
            // 
            this.structuresExtender.SetAttributeName(this.profileCatalog1, null);
            this.structuresExtender.SetAttributeTypeName(this.profileCatalog1, null);
            this.profileCatalog1.BackColor = System.Drawing.Color.Transparent;
            this.structuresExtender.SetBindPropertyName(this.profileCatalog1, null);
            this.profileCatalog1.ButtonText = "Select...";
            this.profileCatalog1.Location = new System.Drawing.Point(265, 25);
            this.profileCatalog1.Name = "profileCatalog1";
            this.profileCatalog1.SelectedProfile = "";
            this.profileCatalog1.Size = new System.Drawing.Size(88, 27);
            this.profileCatalog1.TabIndex = 139;
            this.profileCatalog1.SelectClicked += new System.EventHandler(this.profileCatalog1_SelectClicked);
            this.profileCatalog1.SelectionDone += new System.EventHandler(this.profileCatalog1_SelectionDone);
            // 
            // materialCatalog1
            // 
            this.structuresExtender.SetAttributeName(this.materialCatalog1, null);
            this.structuresExtender.SetAttributeTypeName(this.materialCatalog1, null);
            this.materialCatalog1.BackColor = System.Drawing.Color.Transparent;
            this.structuresExtender.SetBindPropertyName(this.materialCatalog1, null);
            this.materialCatalog1.ButtonText = "albl_Select__";
            this.materialCatalog1.Location = new System.Drawing.Point(266, 61);
            this.materialCatalog1.Name = "materialCatalog1";
            this.materialCatalog1.SelectedMaterial = "";
            this.materialCatalog1.Size = new System.Drawing.Size(88, 27);
            this.materialCatalog1.TabIndex = 140;
            this.materialCatalog1.SelectClicked += new System.EventHandler(this.materialCatalog1_SelectClicked);
            this.materialCatalog1.SelectionDone += new System.EventHandler(this.materialCatalog1_SelectionDone);
            // 
            // Form_att
            // 
            this.structuresExtender.SetAttributeName(this, null);
            this.structuresExtender.SetAttributeTypeName(this, null);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.structuresExtender.SetBindPropertyName(this, null);
            this.ClientSize = new System.Drawing.Size(354, 287);
            this.Controls.Add(this.materialCatalog1);
            this.Controls.Add(this.profileCatalog1);
            this.Controls.Add(this.PolojenieVertikalno);
            this.Controls.Add(this.PolojeniePovorot);
            this.Controls.Add(this.PolojenieGorizontalno);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.NomerSborki);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label24);
            this.Controls.Add(this.PrefixSborki);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.Class);
            this.Controls.Add(this.Namen);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.label20);
            this.Controls.Add(this.Material);
            this.Controls.Add(this.Profile);
            this.Controls.Add(this.label21);
            this.Controls.Add(this.label26);
            this.Name = "Form_att";
            this.Text = "Form2";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.TextBox PrefixSborki;
        private System.Windows.Forms.TextBox Namen;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.TextBox Material;
        private System.Windows.Forms.TextBox Profile;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox Class;
        private System.Windows.Forms.TextBox NomerSborki;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.ComboBox PolojenieGorizontalno;
        private System.Windows.Forms.ComboBox PolojeniePovorot;
        private System.Windows.Forms.ComboBox PolojenieVertikalno;
        private Tekla.Structures.Dialog.UIControls.ProfileCatalog profileCatalog1;
        private Tekla.Structures.Dialog.UIControls.MaterialCatalog materialCatalog1;
    }
}