<UserControl x:Class="SmartWPFElements.Controls.DimensionsForReinforcementControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:SmartWPFElements.Controls" 
             xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
             mc:Ignorable="d" 
             d:DesignHeight="630" d:DesignWidth="800">
    <!--<UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Fusion;component/Themes/Generic.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>-->
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="209*"/>
            <ColumnDefinition Width="153*"/>
        </Grid.ColumnDefinitions>
        <TabControl Margin="5" Grid.Column="0" Grid.Row="1">
            <TabItem Header="Параметры">
                <StackPanel Orientation="Vertical" Grid.Row="1">
                    <GroupBox Header="Размеры и их привязка">
                        <StackPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="DimInsert" Content="Создавать размеры: "/>
                                <ComboBox ItemsSource="{Binding DimensionsInserts, Mode=OneWay}" SelectedIndex="{Binding DimInsert, Mode=TwoWay}"  VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"  IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="L1" Content="Минимальная длина размера по X: "/>
                                <TextBox Text="{Binding L1, Mode=TwoWay}"  VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" />
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="L2" Content="Минимальная длина размера по Y: "/>
                                <TextBox Text="{Binding L2, Mode=TwoWay}"  VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" />
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="L3" Content="Отступ размера по X: "/>
                                <TextBox Text="{Binding L3, Mode=TwoWay}"  VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" />
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="L4" Content="Отступ размера по Y: "/>
                                <TextBox Text="{Binding L4, Mode=TwoWay}"  VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" />
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="DimensionType" Content="Настройки размеров из модели: "/>
                                <ComboBox x:Name="DimensionType"  ItemsSource="{Binding DimensionsTypes, Mode=OneWay}" SelectedItem="{Binding DimensionType, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"  IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                        </StackPanel>
                    </GroupBox>
                    <GroupBox Header="Контур">
                        <StackPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="DiagInsert" Content="Создание диагоналей: "/>
                                <ComboBox x:Name="DiagonalInsert" ItemsSource="{Binding DiagonalInserts, Mode=OneWay}" SelectedIndex="{Binding DiagInsert, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="LineColor" Content="Цвет линий: "/>
                                <ComboBox x:Name="LineColor" ItemsSource="{Binding DrawinColors, Mode=OneWay}" SelectedItem="{Binding LineColor, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="LineType" Content="Тип линий: "/>
                                <ComboBox x:Name="LineType"  ItemsSource="{Binding LineTypes, Mode=OneWay}" SelectedItem="{Binding LineType, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"  IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                        </StackPanel>
                    </GroupBox>
                    <GroupBox Header="Заливка">
                        <StackPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="HatchInsert" Content="Создание заливки: "/>
                                <ComboBox x:Name="HatchlInsert" ItemsSource="{Binding HatchInserts, Mode=OneWay}" SelectedIndex="{Binding HatchInsert, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="HatchColor" Content="Цвет заливки: "/>
                                <ComboBox x:Name="HatchColor" ItemsSource="{Binding DrawinHatchColors, Mode=OneWay}" SelectedItem="{Binding HatchColor, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="HatchName" Content="Имя заливки: "/>
                                <ComboBox x:Name="HatchName"  ItemsSource="{Binding HatchNames, Mode=OneWay}" SelectedItem="{Binding HatchName, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"  IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="ScaleX" Content="Масштаб по X: "/>
                                <TextBox x:Name="ScaleX" Text="{Binding ScaleX, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="ScaleY" Content="Масштаб по Y: "/>
                                <TextBox x:Name="ScaleY" Text="{Binding ScaleY, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="AngleHatch" Content="Угол штриховки: "/>
                                <TextBox x:Name="AngleHatch" Text="{Binding AngleHatch, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150"/>
                            </DockPanel>
                        </StackPanel>
                    </GroupBox>
                    <GroupBox Header="Метка">
                        <StackPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="MarkInsert" Content="Создание метки: "/>
                                <ComboBox x:Name="MarkInsert" ItemsSource="{Binding MarkInserts, Mode=OneWay}" SelectedIndex="{Binding MarkInsert, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                            <DockPanel>
                                <UIControls:WpfFilterCheckBox HorizontalAlignment="Left" VerticalAlignment="Center" AttributeName="MarkType" Content="Тип метки: "/>
                                <ComboBox x:Name="MarkType" ItemsSource="{Binding MarksTypes, Mode=OneWay}" SelectedItem="{Binding MarkType, Mode=TwoWay}" VerticalAlignment="Center" HorizontalAlignment="Right" Height="23" Width="150" IsEditable="True" IsReadOnly="True"/>
                            </DockPanel>
                        </StackPanel>
                    </GroupBox>
                </StackPanel>
            </TabItem>
        </TabControl>
        <Image Source="sp_DimensionsForReinforcement.png" Height="300" VerticalAlignment="Top" HorizontalAlignment="Left" Width="300" Margin="16,5,0,0" Grid.Row="1" Grid.Column="1"/>
    </Grid>
</UserControl>
